### ISSUE TITLE
Posts keep shuffling

### ISSUE THREAD

**Issue by EbenOladutemu** [noxify/gridsome-starter-casper-v3#4]
Thank you for this amazing template.

However, when I make a new post, it doesn't appear as the latest (at the topmost).
Also, posts shuffle from time to time.

How can I make them appear chronologically i.e from newest to oldest?

**Comment by noxify** [comment]
Hi @EbenOladutemu,

the easiest way is to add 

```
sortBy: "created", order: DESC
```

to

https://github.com/noxify/gridsome-starter-casper-v3/blob/master/src/pages/Index.vue#L15

Without having currently an instance to test it, the result should be something like this:

```
entries: allBlog(sortBy: "created", order: DESC, perPage: 9, page: $page) @paginate {
```

If something isn't working, feel free to comment - Otherwise, please close the issue, if it works :)

**Comment by EbenOladutemu** [comment]
It works! Thanks so much for this.
